FROM php:7.4-apache

RUN docker-php-ext-install mysqli pdo_mysql

RUN pecl install xdebug && docker-php-ext-enable xdebug

RUN echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_host=172.17.0.1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_port=9005" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN a2enmod rewrite

WORKDIR /usr/src/app

COPY ./Docker/php/apache-config.conf /etc/apache2/sites-enabled/000-default.conf

EXPOSE 80 443 9005